export const QR_TEMPLATE_CANVAS_WIDTH = 900;
export const QR_TEMPLATE_CANVAS_HEIGHT = 1120;
export const QR_TEMPLATE_DEFAULT_QR_SIZE = 540;
export const QR_TEMPLATE_DEFAULT_QR_X = (QR_TEMPLATE_CANVAS_WIDTH - QR_TEMPLATE_DEFAULT_QR_SIZE) / 2;
export const QR_TEMPLATE_DEFAULT_QR_Y = 260;
